[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Melisa Oubiña", email = "mel_oubi@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "libpass[bcrypt]>=1.9.3",
    "psycopg2-binary>=2.9.13",
    "pydantic-settings>=2.15.0",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "sqlmodel>=0.0.47",
    "tinydb>=4.9.0",
    "uvicorn>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.13.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
