import type { RegistroTalento } from './types/models.js';

export const registrosTalentoDemo: RegistroTalento[] = [
  {
    id: 'REG-001',
    nombreCompleto: 'Maria Garcia Lopez',
    correoElectronico: 'maria.garcia@nexova-demo.com',
    telefono: '+34 612 345 678',
    paisResidencia: 'España',
    anosExperiencia: 6,
    sectorInteres: 'Tecnología',
    nivelIngles: 'Avanzado',
    disponibilidad: '1 mes',
    linkedInUrl: 'https://linkedin.com/in/maria-garcia',
    comentariosAdicionales: 'Experiencia liderando equipos de soporte internacional.',
    aceptoPoliticaDatos: true,
    fechaRegistroISO: '2026-06-10T10:30:00.000Z',
  },
  {
    id: 'REG-002',
    nombreCompleto: 'Carlos Perez Molina',
    correoElectronico: 'carlos.perez@nexova-demo.com',
    telefono: '+1 305 555 0177',
    paisResidencia: 'Estados Unidos',
    anosExperiencia: 10,
    sectorInteres: 'Servicios Financieros',
    nivelIngles: 'Nativo',
    disponibilidad: 'Inmediata',
    linkedInUrl: 'https://linkedin.com/in/carlos-perez-molina',
    comentariosAdicionales: 'Interesado en roles de liderazgo regional.',
    aceptoPoliticaDatos: true,
    fechaRegistroISO: '2026-06-14T14:15:00.000Z',
  },
  {
    id: 'REG-003',
    nombreCompleto: 'Valentina Rojas Diaz',
    correoElectronico: 'valentina.rojas@nexova-demo.com',
    telefono: '+56 9 8765 4321',
    paisResidencia: 'Otro',
    anosExperiencia: 3,
    sectorInteres: 'Retail',
    nivelIngles: 'Intermedio',
    disponibilidad: '2-3 meses',
    comentariosAdicionales: 'Buscando primera oportunidad internacional.',
    aceptoPoliticaDatos: true,
    fechaRegistroISO: '2026-06-20T08:00:00.000Z',
  },
  {
    id: 'REG-004',
    nombreCompleto: 'Lucia Fernandez Torres',
    correoElectronico: 'lucia.fernandez@nexova-demo.com',
    telefono: '+34 699 888 777',
    paisResidencia: 'España',
    anosExperiencia: 12,
    sectorInteres: 'Consultoría',
    nivelIngles: 'Avanzado',
    disponibilidad: 'Solo explorando',
    linkedInUrl: 'https://linkedin.com/in/lucia-fernandez',
    aceptoPoliticaDatos: true,
    fechaRegistroISO: '2026-06-22T16:45:00.000Z',
  },
  {
    id: 'REG-005',
    nombreCompleto: 'Diego Alvarez Romero',
    correoElectronico: 'diego.alvarez@nexova-demo.com',
    telefono: '+34 677 123 999',
    paisResidencia: 'España',
    anosExperiencia: 5,
    sectorInteres: 'Tecnología',
    nivelIngles: 'Básico',
    disponibilidad: 'Inmediata',
    aceptoPoliticaDatos: true,
    fechaRegistroISO: '2026-06-25T09:20:00.000Z',
  },
];
