import type { RegistroTalento } from './types/models.js';

export const registrosTalentoDemo: RegistroTalento[] = [
  {
    'Nombre completo': 'Maria Garcia Lopez',
    'Correo electrónico': 'maria.garcia@nexova-demo.com',
    Teléfono: '+34 612 345 678',
    'País de residencia': 'España',
    'Años de experiencia': 6,
    'Sector de interés': 'Tecnología',
    'Nivel de inglés': 'Avanzado',
    Disponibilidad: '1 mes',
    'LinkedIn (URL del perfil)': 'https://linkedin.com/in/maria-garcia',
    'Comentarios adicionales': 'Experiencia liderando equipos de soporte internacional.',
    'Acepto política de datos': true,
  },
  {
    'Nombre completo': 'Carlos Perez Molina',
    'Correo electrónico': 'carlos.perez@nexova-demo.com',
    Teléfono: '+1 305 555 0177',
    'País de residencia': 'Estados Unidos',
    'Años de experiencia': 10,
    'Sector de interés': 'Servicios Financieros',
    'Nivel de inglés': 'Nativo',
    Disponibilidad: 'Inmediata',
    'LinkedIn (URL del perfil)': 'https://linkedin.com/in/carlos-perez-molina',
    'Comentarios adicionales': 'Interesado en roles de liderazgo regional.',
    'Acepto política de datos': true,
  },
  {
    'Nombre completo': 'Valentina Rojas Diaz',
    'Correo electrónico': 'valentina.rojas@nexova-demo.com',
    Teléfono: '+56 9 8765 4321',
    'País de residencia': 'Otro',
    'Años de experiencia': 3,
    'Sector de interés': 'Retail',
    'Nivel de inglés': 'Intermedio',
    Disponibilidad: '2-3 meses',
    'Comentarios adicionales': 'Buscando primera oportunidad internacional.',
    'Acepto política de datos': true,
  },
  {
    'Nombre completo': 'Lucia Fernandez Torres',
    'Correo electrónico': 'lucia.fernandez@nexova-demo.com',
    Teléfono: '+34 699 888 777',
    'País de residencia': 'España',
    'Años de experiencia': 12,
    'Sector de interés': 'Consultoría',
    'Nivel de inglés': 'Avanzado',
    Disponibilidad: 'Solo explorando',
    'LinkedIn (URL del perfil)': 'https://linkedin.com/in/lucia-fernandez',
    'Acepto política de datos': true,
  },
  {
    'Nombre completo': 'Diego Alvarez Romero',
    'Correo electrónico': 'diego.alvarez@nexova-demo.com',
    Teléfono: '+34 677 123 999',
    'País de residencia': 'España',
    'Años de experiencia': 5,
    'Sector de interés': 'Tecnología',
    'Nivel de inglés': 'Básico',
    Disponibilidad: 'Inmediata',
    'Acepto política de datos': true,
  },
];
